### PR TITLE
Update chart version & add required serviceName field value.

### PR DESCRIPTION
**Pull request by turowicz**
These changes are required for the new Kubernetes versions.

### CODE REVIEW

**Comment by turowicz** [comment]
@winromulus can you help with the CI error?

**Comment by winromulus** [comment]
Investigating. In the meantime please revert the change to the chart version as it's not needed (it's set to the build version as part of the helm package step)

**Comment by turowicz** [comment]
@winromulus reverted `Chart.yaml`

**Comment by turowicz** [comment]
@winromulus approve pls?

**Review by winromulus — APPROVED** [review]
LGTM

**Pull request merged**
